/* eslint quote-props: 0 */
'use strict';

/*
 Add or remove all integrations you want to be bundled into your analytics.js & analytics.min.js file here.
 Integration repos: https://github.com/segment-integrations?utf8=%E2%9C%93&query=analytics.js
 Some also locally
 Make sure that any integrations you have added are also installed and saved as a devDependencies in the package.json
 */
module.exports = {
  // 'adlearn-open-platform': require('@segment/analytics.js-integration-adlearn-open-platform'),
  // 'adobe-analytics': require('@segment/analytics.js-integration-adobe-analytics'),
  // 'adobe-target': require('@segment/analytics.js-integration-adobe-target'),
  // 'adometry': require('@segment/analytics.js-integration-adometry'),
  // 'adroll': require('@segment/analytics.js-integration-adroll'),
  // 'adwords': require('@segment/analytics.js-integration-adwords'),
  // 'adwords-new': require('@segment/analytics.js-integration-adwords-new'),
  // 'alexa': require('@segment/analytics.js-integration-alexa'),
  'amplitude': require('@segment/analytics.js-integration-amplitude'),
  // 'appboy': require('@segment/analytics.js-integration-appboy'),
  // 'appnexus': require('@segment/analytics.js-integration-appnexus'),
  // 'appcues': require('@segment/analytics.js-integration-appcues'),
  // 'atatus': require('@segment/analytics.js-integration-atatus'),
  // 'autosend': require('@segment/analytics.js-integration-autosend'),
  // 'awesm': require('@segment/analytics.js-integration-awesm'),
  // 'bing-ads': require('@segment/analytics.js-integration-bing-ads'),
  // 'blueshift': require('@segment/analytics.js-integration-blueshift'),
  // 'boomtrain': require('@segment/analytics.js-integration-boomtrain'),
  // 'bronto': require('@segment/analytics.js-integration-bronto'),
  // 'bugherd': require('@segment/analytics.js-integration-bugherd'),
  // 'bugsnag': require('@segment/analytics.js-integration-bugsnag'),
  // 'chameleon': require('@segment/analytics.js-integration-chameleon'),
  // 'chartbeat': require('@segment/analytics.js-integration-chartbeat'),
  // 'clevertap': require('@segment/analytics.js-integration-clevertap'),
  // 'clicky': require('@segment/analytics.js-integration-clicky'),
  // 'comscore': require('@segment/analytics.js-integration-comscore'),
  // 'convertro': require('@segment/analytics.js-integration-convertro'),
  // 'crazy-egg': require('@segment/analytics.js-integration-crazy-egg'),
  // 'criteo': require('@segment/analytics.js-integration-criteo'),
  // 'curebit': require('@segment/analytics.js-integration-curebit'),
  // 'customerio': require('@segment/analytics.js-integration-customerio'),
  // 'drift': require('@segment/analytics.js-integration-drift'),
  // 'drip': require('@segment/analytics.js-integration-drip'),
  // 'elevio': require('@segment/analytics.js-integration-elevio'),
  // 'eloqua': require('@segment/analytics.js-integration-eloqua'),
  // 'email-aptitude': require('@segment/analytics.js-integration-email-aptitude'),
  // 'errorception': require('@segment/analytics.js-integration-errorception'),
  // 'evergage': require('@segment/analytics.js-integration-evergage'),
  // 'extole': require('@segment/analytics.js-integration-extole'),
  // 'facebook-conversion-tracking': require('@segment/analytics.js-integration-facebook-conversion-tracking'),
  // 'facebook-custom-audiences': require('@segment/analytics.js-integration-facebook-custom-audiences'),
  // 'facebook-pixel': require('@segment/analytics.js-integration-facebook-pixel'),
  // 'foxmetrics': require('@segment/analytics.js-integration-foxmetrics'),
  // 'friendbuy': require('@segment/analytics.js-integration-friendbuy'),
  // 'frontleaf': require('@segment/analytics.js-integration-frontleaf'),
  // 'fullstory': require('@segment/analytics.js-integration-fullstory'),
  // 'gauges': require('@segment/analytics.js-integration-gauges'),
  // 'get-satisfaction': require('@segment/analytics.js-integration-get-satisfaction'),
  // 'google-analytics': require('@segment/analytics.js-integration-google-analytics'),
  // 'google-tag-manager': require('@segment/analytics.js-integration-google-tag-manager'),
  // 'gosquared': require('@segment/analytics.js-integration-gosquared'),
  'heap': require('@segment/analytics.js-integration-heap'),
  // 'hellobar': require('@segment/analytics.js-integration-hellobar'),
  // 'hindsight': require('@segment/analytics.js-integration-hindsight'),
  // 'hittail': require('@segment/analytics.js-integration-hittail'),
  // 'hotjar': require('@segment/analytics.js-integration-hotjar'),
  // 'hubspot': require('@segment/analytics.js-integration-hubspot'),
  // 'improvely': require('@segment/analytics.js-integration-improvely'),
  // 'inspectlet': require('@segment/analytics.js-integration-inspectlet'),
  'intercom': require('@segment/analytics.js-integration-intercom'),
//   'keen-io': require('@segment/analytics.js-integration-keen-io'),
//   'kenshoo': require('@segment/analytics.js-integration-kenshoo'),
//   'kenshoo-infinity': require('@segment/analytics.js-integration-kenshoo-infinity'),
//   'kissmetrics': require('@segment/analytics.js-integration-kissmetrics'),
//   'klaviyo': require('@segment/analytics.js-integration-klaviyo'),
//   'linkedin-insight-tag': require('@segment/analytics.js-integration-linkedin-insight-tag'),
//   'livechat': require('@segment/analytics.js-integration-livechat'),
//   'localytics': require('@segment/analytics.js-integration-localytics'),
//   'lucky-orange': require('@segment/analytics.js-integration-lucky-orange'),
//   'lytics': require('@segment/analytics.js-integration-lytics'),
//   'madkudu': require('@segment/analytics.js-integration-madkudu'),
//   'marketo': require('@segment/analytics.js-integration-marketo'),
//   'marketo-v2': require('@segment/analytics.js-integration-marketo-v2'),
//   'mixpanel': require('@segment/analytics.js-integration-mixpanel'),
//   'mediamath': require('@segment/analytics.js-integration-mediamath'),
//   'moengage': require('@segment/analytics.js-integration-moengage'),
//   'mojn': require('@segment/analytics.js-integration-mojn'),
//   'mouseflow': require('@segment/analytics.js-integration-mouseflow'),
//   'mousestats': require('@segment/analytics.js-integration-mousestats'),
//   'navilytics': require('@segment/analytics.js-integration-navilytics'),
//   'nielsen-dcr': require('@segment/analytics.js-integration-nielsen-dcr'),
//   'nudgespot': require('@segment/analytics.js-integration-nudgespot'),
//   'olark': require('@segment/analytics.js-integration-olark'),
//   'omniture': require('@segment/analytics.js-integration-omniture'),
//   'onespot': require('@segment/analytics.js-integration-onespot'),
//   'optimizely': require('@segment/analytics.js-integration-optimizely'),
//   'outbound': require('@segment/analytics.js-integration-outbound'),
//   'parsely': require('@segment/analytics.js-integration-parsely'),
//   'perfect-audience': require('@segment/analytics.js-integration-perfect-audience'),
//   'pingdom': require('@segment/analytics.js-integration-pingdom'),
//   //'pinterest-tag': require('@segment/analytics.js-integration-pinterest-tag'),
//   'piwik': require('@segment/analytics.js-integration-piwik'),
//   //'preact': require('@segment/analytics.js-integration-preact'),
//   'qualaroo': require('@segment/analytics.js-integration-qualaroo'),
//   'quantcast': require('@segment/analytics.js-integration-quantcast'),
//   'quanticmind': require('@segment/analytics.js-integration-quanticmind'),
//   'quora-conversion-pixel"': require('@segment/analytics.js-integration-quora-conversion-pixel'),
//   'ramen': require('@segment/analytics.js-integration-ramen'),
//   'rockerbox': require('@segment/analytics.js-integration-rockerbox'),
//   'rocket-fuel': require('@segment/analytics.js-integration-rocket-fuel'),
//   'rollbar': require('@segment/analytics.js-integration-rollbar'),
//   'route': require('@segment/analytics.js-integration-route'),
//   'saasquatch': require('@segment/analytics.js-integration-saasquatch'),
//   'salesforce-dmp': require('@segment/analytics.js-integration-salesforce-dmp'),
//   'salesforce-live-agent': require('@segment/analytics.js-integration-salesforce-live-agent'),
//   'satismeter': require('@segment/analytics.js-integration-satismeter'),
//   'segmentio': require('@segment/analytics.js-integration-segmentio'),
  'sentry': require('@segment/analytics.js-integration-sentry'),
//   'shareasale': require('@segment/analytics.js-integration-shareasale'),
//   'simplereach': require('@segment/analytics.js-integration-simplereach'),
//   'simplifi': require('@segment/analytics.js-integration-simplifi'),
//   'snapengage': require('@segment/analytics.js-integration-snapengage'),
//   'spinnakr': require('@segment/analytics.js-integration-spinnakr'),
//   'steelhouse': require('@segment/analytics.js-integration-steelhouse'),
//   'stripe-radar': require('@segment/analytics.js-integration-stripe-radar'),
//   'supporthero': require('@segment/analytics.js-integration-supporthero'),
//   'tag-injector': require('@segment/analytics.js-integration-tag-injector'),
//   'taplytics': require('@segment/analytics.js-integration-taplytics'),
//   'tapstream': require('@segment/analytics.js-integration-tapstream'),
//   // 'tell-apart': require('@segment/analytics.js-integration-tell-apart'),
//   'totango': require('@segment/analytics.js-integration-totango'),
//   'trackjs': require('@segment/analytics.js-integration-trackjs'),
//   'trakio': require('@segment/analytics.js-integration-trakio'),
//   'tvsquared': require('@segment/analytics.js-integration-tvsquared'),
//   'twitter-ads': require('@segment/analytics.js-integration-twitter-ads'),
//   'userlike': require('@segment/analytics.js-integration-userlike'),
//   'uservoice': require('@segment/analytics.js-integration-uservoice'),
//   'vero': require('@segment/analytics.js-integration-vero'),
//   'visual-website-optimizer': require('@segment/analytics.js-integration-visual-website-optimizer'),
//   'webengage': require('@segment/analytics.js-integration-webengage'),
//   'woopra': require('@segment/analytics.js-integration-woopra'),
//   'wootric': require('@segment/analytics.js-integration-wootric'),
//   'yandex-metrica': require('@segment/analytics.js-integration-yandex-metrica'),
// //  'yellowhammer': require('@segment/analytics.js-integration-yellowhammer'),
//   'zopim': require('@segment/analytics.js-integration-zopim')
};
